package com.dynamiteam.lyahlaundry.tools

const val HOME_FRAGMENT = "homeFragment"
const val OFFERS_FRAGMENT = "offersFragment"
const val TRACK_FRAGMENT = "trackFragment"
const val WALLET_FRAGMENT = "walletFragment"
const val FAVORITE_FRAGMENT = "favoriteFragment"
const val LOGIN_FRAGMENT = "loginFragment"
const val OTP_FRAGMENT = "otpFragment"
const val ALERT_DIALOG_FRAGMENT = "alertDialogFragment"
const val PREF_FIRST_OPEN = "isFirstOpen"
const val PREF_USER_ID = "userId"
const val EMPTY_STRING = ""
const val PREF_USER_NAME = "userName"
const val PREF_USER_EMAIL = "userEmail"
const val PREF_USER_PHONE = "userPhone"
const val PREF_USER_IMAGE = "userAvatar"
const val PREF_USER_RELATION = "relation"
const val PREF_TOKEN = "token"
const val PREF_REFRESH_TOKEN = "refreshToken"

const val APP_PREFERENCES = "APP_PREFERENCES"

const val IS_REGISTERED = "valid_user"
const val OTP_SENT = "otp send"
const val USER_NOT_FOUND = "user not found"
const val CODE_VERIFIED = "Code verifed"
const val CODE_VERIFICATION_FAILED = "Check the code again"
